export const FILTER_COLORS = {
  DEFAULT_BLUE: "#1c397b",
  DEFAULT_BLUE_INACTIVE: "#6482b4",
  BACKGROUND: "#fff",
  TEXT_SHORT_MENU: "#878787",
  BORDER: "#cccccc",
  TEXT_MAIN: "#000",
  BACKGROUND_MAIN: "#f2f2f2",
  BUTTON_HOVER: "#f2f2f2",
  BUTTON_RESET_FILTER: "#FF0000",
  BUTTON_RESET_FILTER_INACTIVE: "#9ca3af",
  SHORT_MENU_RESET_BUTTON_BACKGROUND: "#d6d3d1",
};

export const FILTER_FONT = {
  BOLD_TEXT_FAMILY: "Montserrat, sans-serif",
  MAIN_TEXT_FAMILY: "PT Sans, sans-serif",
};
